// Generated code

#if !DEBUG
#include "Shaders/ShaderProvider/ShaderProvider.h"
const string ShaderProvider::UnpackCode(const uint32_t& h) {
switch (h) {
case 1939412094: return "#version 460 core\nin vec2 fragmentTextureCoords;uniform sampler2D dataTexture;out vec4 color;void main(){color=texture(dataTexture,fragmentTextureCoords);}";
case 776390504: return "#version 460 core\nin vec4 position;in vec2 vertexTextureCoords;out vec2 fragmentTextureCoords;void main(){gl_Position=position;fragmentTextureCoords=vertexTextureCoords;}";
case 3759396228: return "#version 460 core\nlayout(local_size_x=8,local_size_y=8,local_size_z=1)in;struct b{vec4 mask;vec4 mainColor;vec4 edgeColor;float moveSpeed;float turnSpeed;int sensorSize;float sensorOffset;float sensorAngleDegrees;float trailWeight;};layout(std430)restrict readonly buffer colonySettings{b Colony[];};layout(std430)restrict readonly buffer trailBuffer{vec4 Trail[];};restrict writeonly uniform image2D displayTexture;uniform ivec2 size;uniform uint colonySize;void main(){ivec2 c=ivec2(gl_GlobalInvocationID.xy);if(c.x>=size.x||c.y>=size.y)return;vec4 d=Trail[c.y*size.x+c.x];vec4 f=vec4(0);for(uint i=0;i<colonySize;i++){b g=Colony[i];float h=dot(d,g.mask);vec4 j=mix(g.edgeColor,g.mainColor,h);f+=j*h;}imageStore(displayTexture,c,f);}";
case 2410421611: return "#version 460 core\nlayout(local_size_x=8,local_size_y=8,local_size_z=1)in;layout(std430)restrict readonly buffer trailBuffer{vec4 Trail[];};layout(std430)restrict writeonly buffer diffusedTrailBuffer{vec4 DiffusedTrail[];};uniform ivec2 size;uniform float decayRate;uniform float diffuseRate;uniform float globalSpeed;vec4 b(ivec2 c){vec4 d=vec4(0);for(int f=-1;f<2;f++){for(int g=-1;g<2;g++){uint h=clamp(c.y+f,0,size.y-1)*size.x+clamp(c.x+g,0,size.x-1);d+=Trail[h];}}return d/9;}void main(){ivec2 j=ivec2(gl_GlobalInvocationID.xy);if(j.x>=size.x||j.y>=size.y)return;uint k=j.y*size.x+j.x;vec4 l=b(j);float m=clamp(diffuseRate*globalSpeed,.0,1.);vec4 n=(1-m)*Trail[k]+m*l;vec4 p=max(vec4(0),n-decayRate*globalSpeed);DiffusedTrail[k]=p;}";
case 1178242111: return "#version 460 core\nlayout(local_size_x=16,local_size_y=1,local_size_z=1)in;struct b{vec2 position;float angle;int speciesIndex;};struct c{vec4 mask;vec4 mainColor;vec4 edgeColor;float moveSpeed;float turnSpeed;int sensorSize;float sensorOffset;float sensorAngleDegrees;float trailWeight;};layout(std430)restrict readonly buffer colonySettings{c Colony[];};layout(std430)restrict buffer slimeCells{b Cells[];};layout(std430)restrict buffer trailBuffer{vec4 Trail[];};uniform ivec2 size;uniform uint seed;uniform uint userSeed;uniform uint cellCount;uniform float globalSpeed;const float tau=6.2831853072;uint d(uint k){k^=2747636419;k*=2654435769;k^=k>>16;k*=userSeed+1;k*=2654435769;k^=k>>16;k*=2654435769;return k;}float f(uint l){return l/4294967295.;}float g(b m,float n){c p=Colony[m.speciesIndex];int q=p.sensorSize;float r=m.angle+n;vec2 s=vec2(cos(r),sin(r));vec2 t=s*p.sensorOffset+m.position;ivec4 v=ivec4(p.mask*2-1);float w=0;for(int z=-q;z<=q;z++){for(int A=-q;A<=q;A++){uint B=clamp(int(t.y)+z,0,size.y-1)*size.x+clamp(int(t.x)+A,0,size.x-1);w+=dot(v,Trail[B]);}}return w;}void h(uint C,uint D){b E=Cells[C];c F=Colony[E.speciesIndex];float G=f(D);float H=F.turnSpeed*tau*globalSpeed;float I=g(E,0);float J=radians(F.sensorAngleDegrees);float K=g(E,-J);float L=g(E,J);if(I<=L||I<=K){if(I<L&&I<K)Cells[C].angle+=(G-.5)*2*H;else if(K>L)Cells[C].angle-=G*H;else if(L>K)Cells[C].angle+=G*H;}}void j(uint M,uint N){b O=Cells[M];c P=Colony[O.speciesIndex];vec2 Q=vec2(cos(O.angle),sin(O.angle));vec2 R=O.position+Q*P.moveSpeed*globalSpeed;if(R.x<0||R.x>=size.x||R.y<0||R.y>=size.y){R=clamp(R,vec2(0),size-1);Cells[M].angle=f(N)*tau;}else{uint S=int(R.y)*size.x+int(R.x);vec4 T=P.mask*P.trailWeight*globalSpeed+Trail[S];Trail[S]=min(vec4(1),T);}Cells[M].position=R;}void main(){uint U=gl_GlobalInvocationID.x;if(U>=cellCount)return;vec2 V=Cells[U].position;uint W=uint(V.y*size.x+V.x);uint X=d(W+d(seed*100000+U));h(U,X);j(U,d(X));}";
default: return ""; }}
#endif
